SPI/config/routes.rb
Rails.application.routes.draw do



  

  resources :atributosacumulados
  resources :atributosdiarios
  resources :indicadoresacumulados
  resources :indicadoresdiarios
  resources :respuesta
  resources :encuesta
  resources :motivos
  resources :pregunta
  resources :pagos
  resources :mdps
  resources :lineas
  resources :contratos
  resources :fijomovils
  resources :segmentos
  resources :clientes
  get '/historico/index' => 'historico#index', as: 'historico'
  get '/graficos/index' => 'graficos#index', as: 'graficos'
  get '/configuraciones/index' => 'configuraciones#index', as: 'configuraciones'
  get '/ponderacions/index' => 'ponderacions#index', as: 'ponderaciones'
  resources :ponderacions
  devise_for :users
  resources :payments
  resources	:vista2
  root 'vista2#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root :to => 'vista2#index'
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      #'devise/sessions#new'
    end

	end
end

SPI/app/models/mdp.rb
class Mdp < ApplicationRecord
end

SPI/app/controllers/mdps_controller.rb
class MdpsController < ApplicationController
  before_action :set_mdp, only: [:show, :edit, :update, :destroy]

  # GET /mdps
  # GET /mdps.json
  def index
    @mdps = Mdp.all
  end

  # GET /mdps/1
  # GET /mdps/1.json
  def show
  end

  # GET /mdps/new
  def new
    @mdp = Mdp.new
  end

  # GET /mdps/1/edit
  def edit
  end

  # POST /mdps
  # POST /mdps.json
  def create
    @mdp = Mdp.new(mdp_params)

    respond_to do |format|
      if @mdp.save
        format.html { redirect_to @mdp, notice: 'Mdp was successfully created.' }
        format.json { render :show, status: :created, location: @mdp }
      else
        format.html { render :new }
        format.json { render json: @mdp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mdps/1
  # PATCH/PUT /mdps/1.json
  def update
    respond_to do |format|
      if @mdp.update(mdp_params)
        format.html { redirect_to @mdp, notice: 'Mdp was successfully updated.' }
        format.json { render :show, status: :ok, location: @mdp }
      else
        format.html { render :edit }
        format.json { render json: @mdp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mdps/1
  # DELETE /mdps/1.json
  def destroy
    @mdp.destroy
    respond_to do |format|
      format.html { redirect_to mdps_url, notice: 'Mdp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mdp
      @mdp = Mdp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mdp_params
      params.require(:mdp).permit(:id_mdp, :nombre_mdp)
    end
end

SPI/app/helpers/mdps_helper.rb
module MdpsHelper
end

SPI/app/views/mdps/_form.html.erb
<%= form_for(mdp) do |f| %>
  <% if mdp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mdp.errors.count, "error") %> prohibited this mdp from being saved:</h2>

      <ul>
      <% mdp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_mdp %>
    <%= f.number_field :id_mdp %>
  </div>

  <div class="field">
    <%= f.label :nombre_mdp %>
    <%= f.text_field :nombre_mdp %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SPI/app/views/mdps/edit.html.erb
<h1>Editing Mdp</h1>

<%= render 'form', mdp: @mdp %>

<%= link_to 'Show', @mdp %> |
<%= link_to 'Back', mdps_path %>

SPI/app/views/mdps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mdps</h1>

<table>
  <thead>
    <tr>
      <th>Id mdp</th>
      <th>Nombre mdp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mdps.each do |mdp| %>
      <tr>
        <td><%= mdp.id_mdp %></td>
        <td><%= mdp.nombre_mdp %></td>
        <td><%= link_to 'Show', mdp %></td>
        <td><%= link_to 'Edit', edit_mdp_path(mdp) %></td>
        <td><%= link_to 'Destroy', mdp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mdp', new_mdp_path %>

SPI/app/views/mdps/new.html.erb
<h1>New Mdp</h1>

<%= render 'form', mdp: @mdp %>

<%= link_to 'Back', mdps_path %>

SPI/app/views/mdps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id mdp:</strong>
  <%= @mdp.id_mdp %>
</p>

<p>
  <strong>Nombre mdp:</strong>
  <%= @mdp.nombre_mdp %>
</p>

<%= link_to 'Edit', edit_mdp_path(@mdp) %> |
<%= link_to 'Back', mdps_path %>