SPI/config/routes.rb
Rails.application.routes.draw do



  

  resources :atributosacumulados
  resources :atributosdiarios
  resources :indicadoresacumulados
  resources :indicadoresdiarios
  resources :respuesta
  resources :encuesta
  resources :motivos
  resources :pregunta
  resources :pagos
  resources :mdps
  resources :lineas
  resources :contratos
  resources :fijomovils
  resources :segmentos
  resources :clientes
  get '/historico/index' => 'historico#index', as: 'historico'
  get '/graficos/index' => 'graficos#index', as: 'graficos'
  get '/configuraciones/index' => 'configuraciones#index', as: 'configuraciones'
  get '/ponderacions/index' => 'ponderacions#index', as: 'ponderaciones'
  resources :ponderacions
  devise_for :users
  resources :payments
  resources	:vista2
  root 'vista2#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root :to => 'vista2#index'
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      #'devise/sessions#new'
    end

	end
end

SPI/app/models/indicadoresdiario.rb
class Indicadoresdiario < ApplicationRecord
end

SPI/app/controllers/indicadoresdiarios_controller.rb
class IndicadoresdiariosController < ApplicationController
  before_action :set_indicadoresdiario, only: [:show, :edit, :update, :destroy]

  # GET /indicadoresdiarios
  # GET /indicadoresdiarios.json
  def index
    @indicadoresdiarios = Indicadoresdiario.all
  end

  # GET /indicadoresdiarios/1
  # GET /indicadoresdiarios/1.json
  def show
  end

  # GET /indicadoresdiarios/new
  def new
    @indicadoresdiario = Indicadoresdiario.new
  end

  # GET /indicadoresdiarios/1/edit
  def edit
  end

  # POST /indicadoresdiarios
  # POST /indicadoresdiarios.json
  def create
    @indicadoresdiario = Indicadoresdiario.new(indicadoresdiario_params)

    respond_to do |format|
      if @indicadoresdiario.save
        format.html { redirect_to @indicadoresdiario, notice: 'Indicadoresdiario was successfully created.' }
        format.json { render :show, status: :created, location: @indicadoresdiario }
      else
        format.html { render :new }
        format.json { render json: @indicadoresdiario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicadoresdiarios/1
  # PATCH/PUT /indicadoresdiarios/1.json
  def update
    respond_to do |format|
      if @indicadoresdiario.update(indicadoresdiario_params)
        format.html { redirect_to @indicadoresdiario, notice: 'Indicadoresdiario was successfully updated.' }
        format.json { render :show, status: :ok, location: @indicadoresdiario }
      else
        format.html { render :edit }
        format.json { render json: @indicadoresdiario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicadoresdiarios/1
  # DELETE /indicadoresdiarios/1.json
  def destroy
    @indicadoresdiario.destroy
    respond_to do |format|
      format.html { redirect_to indicadoresdiarios_url, notice: 'Indicadoresdiario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicadoresdiario
      @indicadoresdiario = Indicadoresdiario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicadoresdiario_params
      params.require(:indicadoresdiario).permit(:id_ind_diario, :segmento, :isn, :resp_1_2, :resp_4_5, :resolutividad, :version, :fecha, :volumen)
    end
end

SPI/app/helpers/indicadoresdiarios_helper.rb
module IndicadoresdiariosHelper
end

SPI/app/views/indicadoresdiarios/_form.html.erb
<%= form_for(indicadoresdiario) do |f| %>
  <% if indicadoresdiario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(indicadoresdiario.errors.count, "error") %> prohibited this indicadoresdiario from being saved:</h2>

      <ul>
      <% indicadoresdiario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_ind_diario %>
    <%= f.number_field :id_ind_diario %>
  </div>

  <div class="field">
    <%= f.label :segmento %>
    <%= f.number_field :segmento %>
  </div>

  <div class="field">
    <%= f.label :isn %>
    <%= f.text_field :isn %>
  </div>

  <div class="field">
    <%= f.label :resp_1_2 %>
    <%= f.text_field :resp_1_2 %>
  </div>

  <div class="field">
    <%= f.label :resp_4_5 %>
    <%= f.text_field :resp_4_5 %>
  </div>

  <div class="field">
    <%= f.label :resolutividad %>
    <%= f.text_field :resolutividad %>
  </div>

  <div class="field">
    <%= f.label :version %>
    <%= f.number_field :version %>
  </div>

  <div class="field">
    <%= f.label :fecha %>
    <%= f.date_select :fecha %>
  </div>

  <div class="field">
    <%= f.label :volumen %>
    <%= f.number_field :volumen %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SPI/app/views/indicadoresdiarios/edit.html.erb
<h1>Editing Indicadoresdiario</h1>

<%= render 'form', indicadoresdiario: @indicadoresdiario %>

<%= link_to 'Show', @indicadoresdiario %> |
<%= link_to 'Back', indicadoresdiarios_path %>

SPI/app/views/indicadoresdiarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Indicadoresdiarios</h1>

<table>
  <thead>
    <tr>
      <th>Id ind diario</th>
      <th>Segmento</th>
      <th>Isn</th>
      <th>Resp 1 2</th>
      <th>Resp 4 5</th>
      <th>Resolutividad</th>
      <th>Version</th>
      <th>Fecha</th>
      <th>Volumen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indicadoresdiarios.each do |indicadoresdiario| %>
      <tr>
        <td><%= indicadoresdiario.id_ind_diario %></td>
        <td><%= indicadoresdiario.segmento %></td>
        <td><%= indicadoresdiario.isn %></td>
        <td><%= indicadoresdiario.resp_1_2 %></td>
        <td><%= indicadoresdiario.resp_4_5 %></td>
        <td><%= indicadoresdiario.resolutividad %></td>
        <td><%= indicadoresdiario.version %></td>
        <td><%= indicadoresdiario.fecha %></td>
        <td><%= indicadoresdiario.volumen %></td>
        <td><%= link_to 'Show', indicadoresdiario %></td>
        <td><%= link_to 'Edit', edit_indicadoresdiario_path(indicadoresdiario) %></td>
        <td><%= link_to 'Destroy', indicadoresdiario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indicadoresdiario', new_indicadoresdiario_path %>

SPI/app/views/indicadoresdiarios/new.html.erb
<h1>New Indicadoresdiario</h1>

<%= render 'form', indicadoresdiario: @indicadoresdiario %>

<%= link_to 'Back', indicadoresdiarios_path %>

SPI/app/views/indicadoresdiarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id ind diario:</strong>
  <%= @indicadoresdiario.id_ind_diario %>
</p>

<p>
  <strong>Segmento:</strong>
  <%= @indicadoresdiario.segmento %>
</p>

<p>
  <strong>Isn:</strong>
  <%= @indicadoresdiario.isn %>
</p>

<p>
  <strong>Resp 1 2:</strong>
  <%= @indicadoresdiario.resp_1_2 %>
</p>

<p>
  <strong>Resp 4 5:</strong>
  <%= @indicadoresdiario.resp_4_5 %>
</p>

<p>
  <strong>Resolutividad:</strong>
  <%= @indicadoresdiario.resolutividad %>
</p>

<p>
  <strong>Version:</strong>
  <%= @indicadoresdiario.version %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @indicadoresdiario.fecha %>
</p>

<p>
  <strong>Volumen:</strong>
  <%= @indicadoresdiario.volumen %>
</p>

<%= link_to 'Edit', edit_indicadoresdiario_path(@indicadoresdiario) %> |
<%= link_to 'Back', indicadoresdiarios_path %>