SPI/config/routes.rb
Rails.application.routes.draw do



  

  resources :atributosacumulados
  resources :atributosdiarios
  resources :indicadoresacumulados
  resources :indicadoresdiarios
  resources :respuesta
  resources :encuesta
  resources :motivos
  resources :pregunta
  resources :pagos
  resources :mdps
  resources :lineas
  resources :contratos
  resources :fijomovils
  resources :segmentos
  resources :clientes
  get '/historico/index' => 'historico#index', as: 'historico'
  get '/graficos/index' => 'graficos#index', as: 'graficos'
  get '/configuraciones/index' => 'configuraciones#index', as: 'configuraciones'
  get '/ponderacions/index' => 'ponderacions#index', as: 'ponderaciones'
  resources :ponderacions
  devise_for :users
  resources :payments
  resources	:vista2
  root 'vista2#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root :to => 'vista2#index'
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      #'devise/sessions#new'
    end

	end
end

SPI/app/models/pago.rb
class Pago < ApplicationRecord
  belongs_to :linea
  has_and_belongs_to_many :mdps
before_create :set_id_pago
def set_id_pago
	last_id_pago = Pago.maximum(:id_pago)
	self.id_pago = last_id_pago.to_i + 1
end
end

SPI/app/controllers/pagos_controller.rb
class PagosController < ApplicationController
  before_action :set_pago, only: [:show, :edit, :update, :destroy]

  # GET /pagos
  # GET /pagos.json
  def index
    @pagos = Pago.all
  end

  # GET /pagos/1
  # GET /pagos/1.json
  def show
  end

  # GET /pagos/new
  def new
    @pago = Pago.new
  end

  # GET /pagos/1/edit
  def edit
  end

  # POST /pagos
  # POST /pagos.json
  def create
    @pago = Pago.new(pago_params)

    respond_to do |format|
      if @pago.save
        format.html { redirect_to @pago, notice: 'Pago was successfully created.' }
        format.json { render :show, status: :created, location: @pago }
      else
        format.html { render :new }
        format.json { render json: @pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pagos/1
  # PATCH/PUT /pagos/1.json
  def update
    respond_to do |format|
      if @pago.update(pago_params)
        format.html { redirect_to @pago, notice: 'Pago was successfully updated.' }
        format.json { render :show, status: :ok, location: @pago }
      else
        format.html { render :edit }
        format.json { render json: @pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pagos/1
  # DELETE /pagos/1.json
  def destroy
    @pago.destroy
    respond_to do |format|
      format.html { redirect_to pagos_url, notice: 'Pago was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pago
      @pago = Pago.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pago_params
      params.require(:pago).permit(:id_pago, :canal, :orden_compra, :fecha_transaccion, :hora, :cod_retorno, :cod_autorizacion, :monto, :fecha_pago, :fecha_ident_transaccion, :tel_movil, :tel_fijo, :cod_cliente, :documento, :linea_id)
    end
end

SPI/app/helpers/pagos_helper.rb
module PagosHelper
end

SPI/app/views/pagos/_form.html.erb
<%= form_for(pago) do |f| %>
  <% if pago.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pago.errors.count, "error") %> prohibited this pago from being saved:</h2>

      <ul>
      <% pago.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_pago %>
    <%= f.number_field :id_pago %>
  </div>

  <div class="field">
    <%= f.label :canal %>
    <%= f.text_area :canal %>
  </div>

  <div class="field">
    <%= f.label :orden_compra %>
    <%= f.text_area :orden_compra %>
  </div>

  <div class="field">
    <%= f.label :fecha_transaccion %>
    <%= f.date_select :fecha_transaccion %>
  </div>

  <div class="field">
    <%= f.label :hora %>
    <%= f.time_select :hora %>
  </div>

  <div class="field">
    <%= f.label :cod_retorno %>
    <%= f.number_field :cod_retorno %>
  </div>

  <div class="field">
    <%= f.label :cod_autorizacion %>
    <%= f.number_field :cod_autorizacion %>
  </div>

  <div class="field">
    <%= f.label :monto %>
    <%= f.number_field :monto %>
  </div>

  <div class="field">
    <%= f.label :fecha_pago %>
    <%= f.date_select :fecha_pago %>
  </div>

  <div class="field">
    <%= f.label :fecha_ident_transaccion %>
    <%= f.date_select :fecha_ident_transaccion %>
  </div>

  <div class="field">
    <%= f.label :tel_movil %>
    <%= f.number_field :tel_movil %>
  </div>

  <div class="field">
    <%= f.label :tel_fijo %>
    <%= f.number_field :tel_fijo %>
  </div>

  <div class="field">
    <%= f.label :cod_cliente %>
    <%= f.number_field :cod_cliente %>
  </div>

  <div class="field">
    <%= f.label :documento %>
    <%= f.number_field :documento %>
  </div>

  <div class="field">
    <%= f.label :linea_id %>
    <%= f.text_field :linea_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SPI/app/views/pagos/edit.html.erb
<h1>Editing Pago</h1>

<%= render 'form', pago: @pago %>

<%= link_to 'Show', @pago %> |
<%= link_to 'Back', pagos_path %>

SPI/app/views/pagos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pagos</h1>

<table>
  <thead>
    <tr>
      <th>Id pago</th>
      <th>Canal</th>
      <th>Orden compra</th>
      <th>Fecha transaccion</th>
      <th>Hora</th>
      <th>Cod retorno</th>
      <th>Cod autorizacion</th>
      <th>Monto</th>
      <th>Fecha pago</th>
      <th>Fecha ident transaccion</th>
      <th>Tel movil</th>
      <th>Tel fijo</th>
      <th>Cod cliente</th>
      <th>Documento</th>
      <th>Linea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pagos.each do |pago| %>
      <tr>
        <td><%= pago.id_pago %></td>
        <td><%= pago.canal %></td>
        <td><%= pago.orden_compra %></td>
        <td><%= pago.fecha_transaccion %></td>
        <td><%= pago.hora %></td>
        <td><%= pago.cod_retorno %></td>
        <td><%= pago.cod_autorizacion %></td>
        <td><%= pago.monto %></td>
        <td><%= pago.fecha_pago %></td>
        <td><%= pago.fecha_ident_transaccion %></td>
        <td><%= pago.tel_movil %></td>
        <td><%= pago.tel_fijo %></td>
        <td><%= pago.cod_cliente %></td>
        <td><%= pago.documento %></td>
        <td><%= pago.linea %></td>
        <td><%= link_to 'Show', pago %></td>
        <td><%= link_to 'Edit', edit_pago_path(pago) %></td>
        <td><%= link_to 'Destroy', pago, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pago', new_pago_path %>

SPI/app/views/pagos/new.html.erb
<h1>New Pago</h1>

<%= render 'form', pago: @pago %>

<%= link_to 'Back', pagos_path %>

SPI/app/views/pagos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id pago:</strong>
  <%= @pago.id_pago %>
</p>

<p>
  <strong>Canal:</strong>
  <%= @pago.canal %>
</p>

<p>
  <strong>Orden compra:</strong>
  <%= @pago.orden_compra %>
</p>

<p>
  <strong>Fecha transaccion:</strong>
  <%= @pago.fecha_transaccion %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @pago.hora %>
</p>

<p>
  <strong>Cod retorno:</strong>
  <%= @pago.cod_retorno %>
</p>

<p>
  <strong>Cod autorizacion:</strong>
  <%= @pago.cod_autorizacion %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @pago.monto %>
</p>

<p>
  <strong>Fecha pago:</strong>
  <%= @pago.fecha_pago %>
</p>

<p>
  <strong>Fecha ident transaccion:</strong>
  <%= @pago.fecha_ident_transaccion %>
</p>

<p>
  <strong>Tel movil:</strong>
  <%= @pago.tel_movil %>
</p>

<p>
  <strong>Tel fijo:</strong>
  <%= @pago.tel_fijo %>
</p>

<p>
  <strong>Cod cliente:</strong>
  <%= @pago.cod_cliente %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @pago.documento %>
</p>

<p>
  <strong>Linea:</strong>
  <%= @pago.linea %>
</p>

<%= link_to 'Edit', edit_pago_path(@pago) %> |
<%= link_to 'Back', pagos_path %>